## One Hot Encoding

**One Hot Encoding** is a technique used to convert categorical data into a numerical format so that it can be used in machine learning models.

In this method, each unique category is represented as a **binary vector** where:

* Only one value is **1**
* All others are **0**

---

## How it Works

* Identify all **unique categories**
* Assign each category a **separate column**
* Represent the presence of a category with **1** and absence with **0**

---

## Key Characteristics

* No relationship or order is assumed between categories
* Each category is treated independently
* Results in a **sparse matrix** (many zero values)

---

## Advantages

* Simple and easy to understand
* Prevents models from assuming any ordinal relationship
* Works well with many machine learning algorithms

---

## Disadvantages

* Increases **dimensionality**
* Not efficient when there are many categories
* Can lead to **high memory usage**
* In text data, vocabulary size can vary, leading to **inconsistent feature dimensions**
* Models require **fixed-size input**, so changing vocabulary can make training difficult
* **No semantic meaning is captured** (e.g., “king” and “queen” are treated as completely unrelated)
* **Out of Vocabulary (OOV) problem**: New/unseen words cannot be represented

---

* Converts categorical values into binary vectors
* Each category is represented uniquely
* Simple but limited for capturing meaning in NLP tasks

In [50]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [51]:
data = {
    "City": ["Delhi", "Mumbai", "Chennai", "Delhi", "Chennai"],
    "Gender": ["Male", "Female", "Female", "Male", "Female"],
    "Age": [25, 30, 22, 35, 28]
}

df = pd.DataFrame(data)
df

      City  Gender  Age
0    Delhi    Male   25
1   Mumbai  Female   30
2  Chennai  Female   22
3    Delhi    Male   35
4  Chennai  Female   28

In [52]:
categorical_cols = ["City", "Gender"]
df_cat = df[categorical_cols]
df_cat

      City  Gender
0    Delhi    Male
1   Mumbai  Female
2  Chennai  Female
3    Delhi    Male
4  Chennai  Female

In [53]:
encoder = OneHotEncoder(sparse_output=False)

encoded_data = encoder.fit_transform(df_cat)
encoded_data

array([[0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

In [54]:
encoded_columns = encoder.get_feature_names_out(categorical_cols)
encoded_columns

array(['City_Chennai', 'City_Delhi', 'City_Mumbai', 'Gender_Female',
       'Gender_Male'], dtype=object)

In [55]:
encoded_df = pd.DataFrame(encoded_data, columns=encoded_columns)
encoded_df

   City_Chennai  City_Delhi  City_Mumbai  Gender_Female  Gender_Male
0           0.0         1.0          0.0            0.0          1.0
1           0.0         0.0          1.0            1.0          0.0
2           1.0         0.0          0.0            1.0          0.0
3           0.0         1.0          0.0            0.0          1.0
4           1.0         0.0          0.0            1.0          0.0

In [56]:
final_df = pd.concat([df.drop(columns=categorical_cols), encoded_df], axis=1)
final_df

   Age  City_Chennai  City_Delhi  City_Mumbai  Gender_Female  Gender_Male
0   25           0.0         1.0          0.0            0.0          1.0
1   30           0.0         0.0          1.0            1.0          0.0
2   22           1.0         0.0          0.0            1.0          0.0
3   35           0.0         1.0          0.0            0.0          1.0
4   28           1.0         0.0          0.0            1.0          0.0

In [57]:
print(final_df)

   Age  City_Chennai  City_Delhi  City_Mumbai  Gender_Female  Gender_Male
0   25           0.0         1.0          0.0            0.0          1.0
1   30           0.0         0.0          1.0            1.0          0.0
2   22           1.0         0.0          0.0            1.0          0.0
3   35           0.0         1.0          0.0            0.0          1.0
4   28           1.0         0.0          0.0            1.0          0.0